alloy:
  service:
    name: in-cluster-local-grafana-alloy
    namespace: grafana

gateway-helm:
  config:
    envoyGateway:
      telemetry:
        metrics:
          sinks:
          - type: OpenTelemetry
            openTelemetry:
              host: in-cluster-local-grafana-alloy.grafana.svc.cluster.local
              port: 4317
              protocol: grpc
