alloy:
  service:
    name: production-grafana-alloy
    namespace: grafana

envoy-gateway:
  config:
    envoyGateway:
      telemetry:
        metrics:
          sinks:
          - type: OpenTelemetry
            openTelemetry:
              host: production-grafana-alloy.grafana.svc.cluster.local
              port: 4317
              protocol: grpc