linkerd-multicluster:
  # Internal cluster acts as the telemetry hub
  # Gateway enabled with NodePort for cross-cluster service mirroring
  gateway:
    enabled: true
    port: 4143
    serviceType: NodePort
    nodePort: 30143
    probe:
      port: 4191
      nodePort: 30191

  # Grant access to service accounts from production and nonproduction clusters
  # These will be created when those clusters link to internal
  remoteMirrorServiceAccountName: linkerd-service-mirror-remote-access-production,linkerd-service-mirror-remote-access-nonproduction
