linkerd-multicluster:
  # Nonproduction cluster will link to internal for telemetry
  # Gateway disabled - using flat network mode for direct pod-to-pod communication
  gateway:
    enabled: false

  # Grant access to internal cluster
  remoteMirrorServiceAccountName: linkerd-service-mirror-remote-access-in-cluster-local

  # Configure service mirror controller for the internal link
  # This must match the Link resource created by `linkerd multicluster link`
  controllers:
    - link:
        ref:
          name: internal
      logLevel: info
      # Disable gateway mode for flat network
      gateway:
        enabled: false
