linkerd-multicluster:
  # Production cluster will link to internal for telemetry
  # No gateway needed on production (only internal needs gateway)
  gateway:
    enabled: false

  # Grant access to internal cluster
  remoteMirrorServiceAccountName: linkerd-service-mirror-remote-access-in-cluster-local
