alloy:
  service:
    name: grafana-alloy
    namespace: default
    port: 4317

gatewayClass:
  name: main
gateway:
  name: main
  port: 8080
envoyProxy:
  replicas: 2
  serviceType: NodePort
  nodePort: 30080

gateway-helm:
  config:
    envoyGateway:
      gateway:
        controllerName: gateway.envoyproxy.io/gatewayclass-controller
      logging:
        level:
          default: info
      extensionApis: {}

