alloy:
  service:
    name: grafana-alloy
    namespace: default
    port: 4317

gatewayClass:
  name: main
gateway:
  name: main
  port: 8080
envoyProxy:
  replicas: 2
  serviceType: NodePort
  nodePort: 30080

envoy-gateway:
  config:
    envoyGateway:
      logging:
        level:
          default: info
